<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text33_text33</name>
   <tag></tag>
   <elementGuidId>abd8a763-e965-4068-84e6-1c4fea00b139</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text33']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#text33</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9aa17305-9ead-43f1-808c-44156e1e2123</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>86599a2a-95fd-4cfd-9938-755cb123552d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text33</value>
      <webElementGuid>a7fc8b4f-0091-4996-985a-bb5063ce0dba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text33&quot;)</value>
      <webElementGuid>47310011-901e-4424-baea-3f5d213b9e95</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text33']</value>
      <webElementGuid>b192cfaa-e489-4e31-9a10-aa12bf11f7de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[33]</value>
      <webElementGuid>dda03dbb-c4ec-42d2-8c72-193ddd9b7d5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text33']</value>
      <webElementGuid>859ecef4-f888-45d8-ad59-7ff0a259f31d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
