<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text26_text26</name>
   <tag></tag>
   <elementGuidId>9e2d2fb9-d51e-4deb-8222-15a7bb4356ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text26']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#text26</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6910f03f-4b15-4e02-9239-68f050883231</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>536d9238-f426-4692-8cb5-0fc3cf025777</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text26</value>
      <webElementGuid>067b5874-7c8c-43bc-8c97-39d288a13390</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text26&quot;)</value>
      <webElementGuid>fac30bd8-762a-4ed7-84de-eda37bcd8775</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text26']</value>
      <webElementGuid>682a748b-1ea9-4eca-9058-ce9cbbd5a7ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[26]</value>
      <webElementGuid>0bfab913-7f69-4c81-b03f-37447eb88f40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text26']</value>
      <webElementGuid>f6d4912b-c12d-4fc6-8b26-cd7e09f123a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
