<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Radio9_radio10</name>
   <tag></tag>
   <elementGuidId>7c736148-bea8-44cc-86ea-0322be58af97</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='radio10']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#radio10</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>20b5bfe5-7603-4d5b-a27e-fb56c101a4bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>a2ac7d78-37d1-4cf0-ae19-410b1a147e7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radio10</value>
      <webElementGuid>b982b199-45b2-4018-a6bf-de8628c5eb1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Radio10</value>
      <webElementGuid>fca6eef4-9dca-4e3e-babd-046c4558e2e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radio10&quot;)</value>
      <webElementGuid>f0202359-21a6-461d-9a9c-5db10fa7c7f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='radio10']</value>
      <webElementGuid>4bc76f1e-343f-41ac-bf00-cf127889a471</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[30]</value>
      <webElementGuid>3c1409ba-1599-4b79-ba41-a6e80c564d38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'radio10']</value>
      <webElementGuid>336ac955-1371-45cf-a270-f0f1ca5ff916</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
