<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Checkbox1</name>
   <tag></tag>
   <elementGuidId>4d4b5623-8ae2-4662-909f-5c5a4c4ad03a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Text10:'])[1]/following::label[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>f72866c0-bda6-4d41-8bb0-b0f7641c34a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Checkbox1</value>
      <webElementGuid>d58c7364-a591-4035-9021-a1282f9877c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/form[1]/label[11]</value>
      <webElementGuid>23244c3b-9258-4b34-a8e3-f67c48107451</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Text10:'])[1]/following::label[1]</value>
      <webElementGuid>6f3a5ced-68ea-4e95-ba85-324d7ebfb19a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Text9:'])[1]/following::label[2]</value>
      <webElementGuid>c4f8a93e-3989-4ee8-b541-b9e96a0f448c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Checkbox2'])[1]/preceding::label[1]</value>
      <webElementGuid>f080e250-67bc-4d67-ae44-b97b3333e6c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Checkbox3'])[1]/preceding::label[2]</value>
      <webElementGuid>d6edfa63-0c9c-4d11-b8d9-0895d1035fdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Checkbox1']/parent::*</value>
      <webElementGuid>2ba1cb2e-1e2b-4330-b7e3-a1267510b623</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[11]</value>
      <webElementGuid>1f5c9bf5-4227-49ee-bb28-16c0660b36d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Checkbox1' or . = 'Checkbox1')]</value>
      <webElementGuid>f7db1a19-ad6b-4ebd-a833-86d18fbd87b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
